name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 28.1

    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Test the project
        run: eldev test
